mv RelValTTbar_13TeV_HIPNoSIMU0p6-MITI_muonPOGNtuple_METMoriond17Filter.root RelValTTbar_13TeV_HIPSIMU0p6-MITI_muonPOGNtuple_METMoriond17Filter.root
mv RelValTTbar_13TeV_HIPNoSIMU0p6-NoMITI_muonPOGNtuple_METMoriond17Filter.root RelValTTbar_13TeV_HIPSIMU0p6-NoMITI_muonPOGNtuple_METMoriond17Filter.root
mv RelValTTbar_13TeV_HIPNoSIMU0p8-MITI_muonPOGNtuple_METMoriond17Filter.root RelValTTbar_13TeV_HIPSIMU0p8-MITI_muonPOGNtuple_METMoriond17Filter.root
mv RelValTTbar_13TeV_HIPNoSIMU0p8-NoMITI_muonPOGNtuple_METMoriond17Filter.root RelValTTbar_13TeV_HIPSIMU0p8-NoMITI_muonPOGNtuple_METMoriond17Filter.root
mv RelValTTbar_13TeV_HIPNoSIMU1p2-MITI_muonPOGNtuple_METMoriond17Filter.root RelValTTbar_13TeV_HIPSIMU1p2-MITI_muonPOGNtuple_METMoriond17Filter.root
mv RelValTTbar_13TeV_HIPNoSIMU1p2-NoMITI_muonPOGNtuple_METMoriond17Filter.root RelValTTbar_13TeV_HIPSIMU1p2-NoMITI_muonPOGNtuple_METMoriond17Filter.root
